### ISSUE TITLE
Not working with Postgres10

### ISSUE THREAD

**Issue by asr1901** [dalibo/powa#102]
POWA doesn't seem to work with Postgres 10 because of pg_qualstats dependency.  I am trying to install POWA on a postgres10 machine with no success because adding "pg_qualstats" to shared preload libraries causes the instance to crash/not start.  POWA then fails when the database is brought up without pg_qualstats

**Comment by rjuju** [comment]
Thanks for the report.

Since it's apparently only pg_qualstats related, I'll close this issue and we'll try to fix the problem in https://github.com/dalibo/pg_qualstats/issues/18.

Feel free to reopen this issue if any other problem exists for powa in pg10.
