### ISSUE TITLE
[Chrome] custom date selectors are too large 

### ISSUE THREAD

**Issue by daamien** [dalibo/powa#26]
With Chrome, the custom date selector have a 100% width.

![screenshot - 08102014 - 10 11 34](https://cloud.githubusercontent.com/assets/165646/4555857/eb8f33c8-4ec2-11e4-927d-981aa45038ce.png)

Also you center the "date bar" on the page and leave some space between the date bar and the graphs

**Comment by rjuju** [comment]
Fixed when powa 2 was released.
