### ISSUE TITLE
Connection with database

### ISSUE THREAD

**Issue by czachson** [dalibo/powa#46]
Hello
I have just installed POWA and I'm tryin to connect it with postgresql 9.3 database (using 1.x version of POWA) and I just see "No database found.". Is this caused by just empty database or I may did something wrong? 

Pawel

**Comment by rjuju** [comment]
Hello,

It looks like you're using an old version of PoWA 1. Please try with the release 1.2.1 if you still have this issue.

**Comment by rjuju** [comment]
Hello,

any update on this issue ?

Regards.
