### ISSUE TITLE
requires btree_gist

### ISSUE THREAD

**Issue by shribe** [dalibo/powa#49]
The install docs do not mention that btree_gist is required.

**Comment by rdunklau** [comment]
The requirement is implied in the quickstart guide by using the provided install_all.sh script, and the instruction is clearly stated in the powa-archivist installation guide.

I made the dependency on postgresql contrib modules more explicit in the above mentioned commit.

Feel free to re-open the issue if its not sufficient.

**Comment by shribe** [comment]
??? install_all.sh does not reference btree_gist at all. The docs (& install_all.sh) still say to edit postgresql.conf thus:

shared_preload_libraries='pg_stat_statements,powa,pg_stat_kcache,pg_qualstats'

which is incorrect. While the changes to the docs make it clear that contrib modules are needed, it would be nice to specify which ones need to be installed.

**Comment by rdunklau** [comment]
I must be missing something: what is wrong with the shared_preload_libraries suggested configuration ? btree_gist should not be loaded at startup.

The install_all.sh script executes the install_all.sql file, which creates the btree_gist extension.  

As per your suggestion, I added the specific modules in the documentation.

**Comment by shribe** [comment]
"btree_gist should not be loaded at startup"

I did not realize that.

"The install_all.sh script executes the install_all.sql file, which creates the btree_gist extension."

That cannot happen if it's not built--you get an error. So, basically, if you follow the instructions with a clean PG build, you get an error about btree_gist not being available. (As well as pg_stat_statements, but that's more clear because it's at least mentioned.)

**Comment by rdunklau** [comment]
I hope the latest commit took care of that. Can you confirm that it is sufficient ?

**Comment by shribe** [comment]
Yes. That would be enough of a clue for those who build from source.

**Comment by rdunklau** [comment]
Thank you for taking the time to report this issue and providing feedback !
