### ISSUE TITLE
glitch in summarizing query stats

### ISSUE THREAD

**Issue by shribe** [dalibo/powa#51]
consider these entries from pg_stat_statements:

 userid | dbid  |  queryid   |                       query                        | calls |    total_time    | rows  
--------+-------+------------+----------------------------------------------------+-------+------------------+-------
  16384 | 16388 | 3025283004 | set search_path to v2,v0; select log.setup_conn(); |   210 |          290.964 |   210 
  16384 | 16388 | 1610272070 | set search_path to v2,v0; select log.setup_conn(); |   210 |            8.975 |     0 
     10 | 16388 | 3025283004 | set search_path to v2,v0; select log.setup_conn(); | 44052 | 1352.91499999995 | 44052 
     10 | 16388 | 1610272070 | set search_path to v2,v0; select log.setup_conn(); | 44052 | 250.063999999903 |     0 

See the attached screenshot.
![remote desktopscreensnapz001](https://cloud.githubusercontent.com/assets/3246499/7863238/7825f7f2-0518-11e5-8e92-911ad7de0d71.png)

**Comment by shribe** [comment]
BTW, I apologize for putting these on the wrong repository. Forgot I was in docs, not where it belonged.

**Comment by rdunklau** [comment]
Thats fine, this repository acts as a catch-all for issues related to the various components.

Could you explain more precisely what the issue is here ?

**Comment by shribe** [comment]
4 entries in pg_stat_statements, 4 entries shown in the web UI

But in the web UI, it looks like some individual entries are sums of the 4 entries in pg_stat_statements, while others are either pulled from a single entry or are an average of the 2 entries for a user id.

I don't care much whether all entries are shown, or they are coalesced into sums/averages as appropriate. But it should be consistent one way or another.

So we have 2 very different values for total times, divided by the same counts, leading to two very different average times. I believe the counts are sums of all 4 while the total times are either one entry or sums of two, so the average times are incorrect. (It's also possible that the total times are from a single arbitrarily chosen row, but however it happens, calculation of total time and counts are inconsistent.)

**Comment by rjuju** [comment]
Hello,

The last commit (dalibo/powa-web@59515a0386db73f9957ee4b64bebe9321e98bb13) should have fixed this issue.

Could you test to see if everything is ok ?

**Comment by rjuju** [comment]
Hello,

did you have time to test the provided fix ?

Regards.
