### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by indreek** [dalibo/powa#53]
According to documentation http://powa.readthedocs.org/en/latest/quickstart.html there is no requirement for unzip.  Empty ubuntu doesn't have it installed. So while running ./install_all.sh i got error:
root@pg-develop:/tmp/powa-archivist-REL_2_0_0# ./install_all.sh
./install_all.sh: line 6: cd: pg_qualstats-master/: No such file or directory
./install_all.sh: line 13: cd: pg_stat_kcache-master/: No such file or directory
rm: cannot remove ‘master.zip’: No such file or directory

It all got fixed after installing unzip. So maybe you can write a hint for noobs like me :)

Thanks,
Indrek

**Comment by rdunklau** [comment]
Thank you for the report !

Instead of adding documentation on the need to install unzip, I changed the script to use .tar.gz instead:

https://github.com/dalibo/powa-archivist/commit/bf6c9df607a99f4b2a7160d9c85143b4613301ea
