### ISSUE TITLE
Can not login to web interface

### ISSUE THREAD

**Issue by hazhirhajian** [dalibo/powa#54]
Hi,

I have install powa following the instruction on website and now I can not login to the web interface. I use postgres as user name and it password. Here is the error I get everytime I try to login:

[root@XXX powa-web-2.0.11]# ./powa-web
[I 150907 15:35:05 web:1392] 302 GET / (10.10.0.3) 1.73ms
[W 150907 15:35:05 web:1392] 403 GET /login/?next=%2F (10.10.0.3) 74.19ms
[E 150907 15:36:08 user:20] No module named postgresql+psycopg2
[W 150907 15:36:08 web:1392] 403 POST /login/?next=%2F (10.10.0.3) 181.16ms
[E 150907 15:36:22 user:20] No module named postgresql+psycopg2
[W 150907 15:36:22 web:1392] 403 POST /login/?next=%2F (10.10.0.3) 2.90ms
[E 150907 15:56:06 user:20] No module named postgresql+psycopg2

psycopg2 is already installed on the machine.
[root@XXX ~]# yum list all | grep psycopg2
python-psycopg2.x86_64                      2.0.14-2.el6                 @base
python-psycopg2-debuginfo.x86_64            2.0.14-2.el6                 debug
python-psycopg2-doc.x86_64                  2.0.14-2.el6                 base
python27-python-psycopg2-debuginfo.x86_64   2.5.1-1.el6.centos.alt       debug
python33-python-psycopg2-debuginfo.x86_64   2.5.1-1.el6.centos.alt       debug

What am I doing wrong?

**Comment by rdunklau** [comment]
What version of sqlalchemy do you use ?

**Comment by hazhirhajian** [comment]
python-sqlalchemy.noarch             0.5.5-3.el6_2

**Comment by rdunklau** [comment]
PoWA is compatible with sqlalchemy >= 0.7.8. Re-browsing the docs, it seems this information is missing. Did you install sqlalchemy as a dependency from powa-web, or was it already installed from your centos packages ?

**Comment by rdunklau** [comment]
Excuse me, that's implied by the way you gave your version. The instructions imply you install powa-web with pip.

**Comment by hazhirhajian** [comment]
Yes, I used pip to install powa-web and  sqlalchemy was already installed. So shoudl I upgrade sqlalchemy to higher version!
