### ISSUE TITLE
Wrong timezone on graph

### ISSUE THREAD

**Issue by fluancefg** [dalibo/powa#55]
Hi,

When I display the graph, the times are always displayed with GMT, even if the timezone of our DB is set to GMT+2. Is it possible to use the change/chose the timezone to be displayed in the UI ?

Thank you

**Comment by rjuju** [comment]
Hello,

There's no option to set the displayed timezone. The timestamp should be automatically converted to your current timezone. Is your computer configured to timezone GMT ?

**Comment by fluancefg** [comment]
Hello,

My current timezone is configured to CEST: jeu oct 15 19:17:44 CEST 2015. However, all the graphs are displayed with GMT timezone and a gap of two hours.
Btw, the timestmap is in the same timezone on the server, so it is converted back to GMT.

**Comment by fluancefg** [comment]
Any news or advices about that ?
I still have a gap between the time displayed in the calendar and the one displayed on the graph (which is always set to GMT).

**Comment by rjuju** [comment]
Hello,

We looked at this and the js library used should display timestamps in local timezone, which it obviously does not :(

We'll continue to investigate on it, hoping to fix that issue soon.

**Comment by rjuju** [comment]
Hello,

Sorry about the delay, this issue is now be fixed in https://github.com/dalibo/powa-web/commit/ba29159e1dbe09513590335ca94ec0c1a935945d.

**Comment by fluancefg** [comment]
Hi,

Thanks for the fix. Sorry, I did not see your email before :-\

2016-12-02 20:19 GMT+01:00 Julien Rouhaud <notifications@github.com>:
