### ISSUE TITLE
Avoid need of SUPER privilege

### ISSUE THREAD

**Issue by tbe** [dalibo/powa#56]
To avoid using superuser privileges and give these to developer accounts, some wrappers would be great.

All calls to system views could be wrapped in a function with ``SECURITY DEFINER``.

**Comment by rjuju** [comment]
Which version of PoWA are you using ?

The superuser requirement was originally added for security reasons. We got feedback that this requirement was too strong, so it has been removed in PoWA v2. You just need to ensure the user(s) connecting to the UI has sufficient privileges to read the tables in the powa database, and also to connect to other databases for advanced features like index suggestion.

**Comment by tbe** [comment]
We use 2.0.2. If this is already fixed there is only a documentation bug left ;)

http://powa.readthedocs.org/en/latest/security.html

**Comment by rjuju** [comment]
Indeed :)

I just update the documentation. Thanks a lot for the report!
