### ISSUE TITLE
Impossible to suggest indexes

### ISSUE THREAD

**Issue by guibw** [dalibo/powa#57]
I just installed the latest powa (3.0.0), plus pg_qualstats, pg_stat_statements and pg_stat_kcache.

However, I am getting a "Impossible to suggest indexes: please enable support for pg_qualstats in powa See the documentation for more information".

On "Server Configuration" pg_qualstats shows as available, installad and handled.

What am I missing ?
Thanks.

**Comment by rjuju** [comment]
Hello,

Indeed, the error message is not really helping, I'll try to enhance it.
I think your issue is that you have a too old version of pg_qualstats for powa 3. Can you check if you have pg_qualstatst v0.0.7 ? If not, upgrading should solve your issue.

Regards

**Comment by guibw** [comment]
Yes, I had pg_qualstats on 0.0.6. Updated to 0.0.7 and it seems to be working now.

Just a few sidenotes:

http://dalibo.github.io/powa/ - download button is version "REL_2_0_0"
https://github.com/dalibo/powa-archivist/blob/master/INSTALL.md - install instructions refer to "2_0_0" and has no references to pg_qualstats nor pg_stat_kcache.

**Comment by rjuju** [comment]
Thanks for the reports ! I just changed the download button.

About the INSTALL.md doc, I think it'd be really better to redirect to powa.readthedocs.org, as it should be the most complete and up to date documentation.
