### ISSUE TITLE
server name in header

### ISSUE THREAD

**Issue by superette** [dalibo/powa#71]
hello powa team !
if you please can make server name appears in the header of powa page it would be great.

**Comment by rjuju** [comment]
I like the idea. We should also dispay what the server name points to (IP or dns specified).

**Comment by rjuju** [comment]
Done in commit https://github.com/dalibo/powa-web/commit/c971dda3e87d693099d3ff7eda5ffe0147f64212

**Comment by superette** [comment]
Thank you Julien !
