### ISSUE TITLE
eroor when open the web ui

### ISSUE THREAD

**Issue by HaiquanHe** [dalibo/powa#77]
After installation, I start the powa-web , and access it . but not data found ,and can't display any data.
the output log show :
InvalidRequestError: Ambiguous column name 's' in result set! try 'use_label

**Comment by rjuju** [comment]
Hello,

Which version of powa-web are you using, which version of SQLAlchemy?

**Comment by HaiquanHe** [comment]
powa-web  is 3.0.2 ,
SQLAlchemy is  python-sqlalchemy0.8-0.8.2-4.el6.x86_64.

**Comment by viodlen** [comment]
Hi,

I could not reproduce the bug with the same version of SQLAlchemy and powa-web. I tried with both python2 and python3.

Can you give us a bit more information? We'd need:

- your version of python and postgresql
- the complete backtrace
- the page you're trying to access

Also in database powa:
- the extensions that are installed in your postgres (`\dx`)
- the shared preload libraries (`show shared_preload_libraries;`)
- the functions enabled in powa (`select * from powa_functions;`)

Thanks in advance!

**Comment by rjuju** [comment]
Hello,

Do you still have this issue?
