### ISSUE TITLE
EnterpriseDB PostgreSQL 9.5

### ISSUE THREAD

**Issue by carvalhorogerioc** [dalibo/powa#78]
Dear Sir,
I was trying to install POWA with EnterpriseDB PostgreSQL 9.5.3, but when start the database show this message:
$ pg_ctart start
2016-06-19 15:12:04 BRT [14048]: [1-1] user=,db= FATAL:  incompatible library "/opt/PostgreSQL/9.5/lib/postgresql/powa.so": version mismatch
2016-06-19 15:12:04 BRT [14048]: [2-1] user=,db= DETAIL:  Server is version 9.5, library is version 9.4.

Can you help me ?

Best regards

Rogerio Carvalho

**Comment by rjuju** [comment]
Hello,

The powa lib is in version 9.4 and your database is 9.5, which is quite surprising since the target folder is named 9.5. How did you intall powa, did you compile it or used some package? Or perhaps you upgraded the server and copied instead of upgrading this lib?

Regards.

**Comment by carvalhorogerioc** [comment]
Julian,

     I compiled, steps passed in Quick start install. After changed 
parameter to :

shared_preload_libraries = 
'pg_stat_statements,powa,pg_stat_kcache,pg_qualstats'


Best regards,

  

Rogério Cunha Carvalho
"Muitos são os planos no coração do homem, mas o que prevalece é o propósito do Senhor." Provérbios 19:21
"There are many plans in a man's heart; nevertheless the counsel of the LORD, that shall stand." Proverbs 19:21

Em 19-06-2016 17:31, Julien Rouhaud escreveu:

**Comment by rjuju** [comment]
Do you have multiple postgresql versions installed?

Can you return the output of the following command, as the user used to compile powa-archivist

```
pg_config --version
sudo pg_config --version
```

If the first one return 9.4.x and the second one 9.5.x, this is the cause of your issue. You can solve by executing this, in the powa-archivist souce code directory :

```
make clean
sudo make install
```

**Comment by carvalhorogerioc** [comment]
Bingo......the problem was solve.

Best regards,


  

Rogério Cunha Carvalho
"Muitos são os planos no coração do homem, mas o que prevalece é o propósito do Senhor." Provérbios 19:21
"There are many plans in a man's heart; nevertheless the counsel of the LORD, that shall stand." Proverbs 19:21

Em 20-06-2016 09:34, Julien Rouhaud escreveu:

**Comment by rjuju** [comment]
Good news :)
