### ISSUE TITLE
hypopg extension installed but power still shows Install hypopg for solution validation

### ISSUE THREAD

**Issue by goodwill** [dalibo/powa#93]
As title, PostgreSQL 9.5.4 with all recommended extensions installed

**Comment by rjuju** [comment]
Hello,

Documentation may be unclear, but hypopg extension has to be installed on every database you want to run the wizard tool on.  If that's the case, can you show the result of
```sql
SELECT * FROM pg_extension
```

on the target database?

**Comment by goodwill** [comment]
Gotcha! Just wanna check so only hypopg needs to be on every database, all other extensions just needs to be on powa db right?

**Comment by rjuju** [comment]
Exactly :)
